version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aks-rony/americakingstones
    container_name: app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ro30182
      SESSION_DRIVE: redis
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc.php/conf./local.ini

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: aks-rony/nginx
    container_name: webserver
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./resources/views/frontend/homepage:/usr/share/nginx/html:ro

    environment:
      - VIRTUAL_HOST=americakingstones.com,www.americakingstones.com
      - LETSENCRYPT_HOST=americakingstones.com,www.americakingstones.com
      - LETSENCRYPT_EMAIL=rony@americakingstones.com

    depends_on:
      - app
      - nginx-proxy
      - letsencrypt

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ro30182
      MYSQL_DATABASE: warehouse #Rony
  redis:
    image: redis:latest
    container_name: redis

volumes:
  certs:
  html:
  vhostd:
  dbdata:
    driver: local
