version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomw1808/americakingstones
    container_name: app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ro30182
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc.php/conf./local.ini

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: tomw1808/nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ro30182
      MYSQL_DATABASE: warehouse #Rony

volumes:
  dbdata:
    driver: local
