version: "3.1"

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ro30182
      MYSQL_DATABASE: warehouse #Rony

volumes:
  db:
